# folder structure
source_dir: "source"
theme_dir: "themes"
output_dir: "static"

# general info
title: "with flags flying"
description: "mie's blog"
author: "mie"
#domain: "http://blog.com/" - tbd

# themes
theme: "default"

# internal parameters
# for index pages:
posts_by_page: 10
tags:
  pacers: pacers
  soap: soap
  nba: nba
  ruby: ruby